// <auto-generated />
using CSProjeDemo2.DataAccess.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSProjeDemo2.DataAccess.Migrations
{
    [DbContext(typeof(PersonelDbContext))]
    [Migration("20240317191513_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSProjeDemo2.Model.Models.BaseModel.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalismaSaati")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("SaatlikUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personeller");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Personel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CSProjeDemo2.Model.Models.Memur", b =>
                {
                    b.HasBaseType("CSProjeDemo2.Model.Models.BaseModel.Personel");

                    b.Property<int>("Derece")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Memur");
                });

            modelBuilder.Entity("CSProjeDemo2.Model.Models.Yonetici", b =>
                {
                    b.HasBaseType("CSProjeDemo2.Model.Models.BaseModel.Personel");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Yonetici");
                });
#pragma warning restore 612, 618
        }
    }
}
